# Generated by Django 6.0.1 on 2026-01-30 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAgentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('model_name', models.CharField(default='gpt-4', max_length=100)),
                ('temperature', models.FloatField(default=0.7)),
                ('max_tokens', models.IntegerField(default=2000)),
                ('system_prompt', models.TextField(default='Você é um assistente especializado em análise de supply chain e logística.\nSua função é:\n1. Interpretar requisições de relatórios de usuários\n2. Identificar KPIs relevantes para a análise solicitada\n3. Acessar dados de estoque, vendas e logística\n4. Gerar insights acionáveis\n5. Criar recomendações baseadas em dados\n\nSempre estruture seus relatórios com:\n- Executive Summary\n- KPIs principais\n- Análise detalhada\n- Recomendações\n- Próximos passos')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('user', 'User Message'), ('ai', 'AI Response')], max_length=10)),
                ('content', models.TextField()),
                ('status', models.CharField(blank=True, choices=[('analyzing', 'Analyzing'), ('planning', 'Planning'), ('etl', 'ETL Processing'), ('generating', 'Generating'), ('complete', 'Complete')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processing_time_ms', models.IntegerField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_reports.chatsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('report_data', models.JSONField(default=dict)),
                ('insights', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exported_formats', models.JSONField(default=list)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='ai_reports.chatsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
