# Generated by Django 6.0.1 on 2026-02-02 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_reports', '0002_chatmessage_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='agent_model',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='agent_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='report_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='report_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
